import streamlit as st
import requests
from datetime import date
from PIL import Image
import os

# Define the path to the images folder
image_folder = 'images'

# Load local JPEG images from the images folder
image1 = Image.open(os.path.join(image_folder, 'logo-no-background.png'))

st.image(image1, width=200)

st.write("---")

st.write("## Competitor Flight Fare Predictions")

st.write("Provide flight details to get price predictions for your competitors' flights.")

st.write("---")

# Create four columns
col1, col2, col3, col4, col5, col6, col7, col8, col9 = st.columns(9)

#### Airports
OLD_Origin_Airports = [
 'AAE - Annaba',
 'AAL - Aalborg',
 'AAR - Aarhus',
 'ABJ - Abidjan',
 'ABV - Abuja',
 'ABZ - Aberdeen',
 'ACC - Accra',
 'ACE - Arrecife',
 'ACH - Altenrhein',
 'ADA - Adana',
 'ADB - Izmir',
 'ADD - Addis Ababa',
 'ADF - Adiyaman',
 'AES - Aalesund',
 'AEY - Akureyri',
 'AGA - Agadir',
 'AGH - Angelholm/Helsingborg',
 'AGP - Malaga',
 'AHB - Abha',
 'AHO - Alghero',
 'AHU - Al Hoceima',
 'AJA - Ajaccio',
 'AJF - Sakaka Al Jouf',
 'AJI - Agri',
 'AKX - Aktyubinsk',
 'ALA - Almaty',
 'ALC - Alicante',
 'ALF - Alta',
 'ALG - Algiers',
 'AMM - Amman',
 'AMS - Amsterdam',
 'ANR - Antwerp',
 'AOE - Eskisehir',
 'AOI - Ancona',
 'AOK - Karpathos',
 'AQI - Qaisumah',
 'AQJ - Aqaba',
 'ARN - Stockholm',
 'ASB - Ashgabat',
 'ASR - Kayseri',
 'ASW - Aswan',
 'ATH - Athens',
 'AUH - Abu Dhabi',
 'AUR - Aurillac',
 'AXD - Alexandroupolis',
 'AYT - Antalya',
 'BAH - Manama',
 'BAL - Batman',
 'BAY - Baia Mare',
 'BBU - Bucharest',
 'BCM - Bacau',
 'BCN - Barcelona',
 'BDS - Brindisi',
 'BDU - Bardufoss',
 'BEG - Belgrade',
 'BEM - Bossembele',
 'BEN - Benghazi',
 'BER - Berlin',
 'BES - Brest',
 'BEY - Beirut',
 'BFS - Belfast',
 'BGG - Bongouanou',
 'BGO - Bergen',
 'BGW - Baghdad',
 'BGY - Bergamo',
 'BHD - Belfast',
 'BHH - Bisha',
 'BHK - Bukhara',
 'BHX - Birmingham',
 'BIA - Bastia',
 'BIO - Bilbao',
 'BIQ - Biarritz',
 'BJA - Bejaia',
 'BJL - Banjul',
 'BJV - Milas',
 'BJZ - Badajoz',
 'BKO - Bamako',
 'BLJ - Batna',
 'BLL - Billund',
 'BLQ - Bologna',
 'BMA - Stockholm',
 'BNX - Banja Luka',
 'BOD - Bordeaux',
 'BOH - Bournemouth',
 'BOJ - Bourgas',
 'BOO - Bodo',
 'BRE - Bremen',
 'BRI - Bari',
 'BRN - Berne',
 'BRQ - Brno',
 'BRS - Bristol',
 'BRU - Brussels',
 'BSK - Biskra',
 'BSL - Mulhouse/basel',
 'BSR - Basra',
 'BTS - Bratislava',
 'BUD - Budapest',
 'BUS - Batumi',
 'BVA - Paris',
 'BVC - Boa Vista',
 'BVE - Brive-La-Gaillarde',
 'BWK - Bol',
 'BZG - Bydgoszcz',
 'BZO - Bolzano',
 'BZR - Beziers',
 'CAG - Cagliari',
 'CAI - Cairo',
 'CCF - Carcassonne',
 'CDG - Paris',
 'CFE - Clermont-Ferrand',
 'CFK - Chefornak, AK',
 'CFN - Carrickfinn',
 'CFR - Caen',
 'CFU - Kerkyra',
 'CGN - Cologne',
 'CHQ - Chania',
 'CIA - Rome',
 'CIT - Shimkent',
 'CIY - Comiso',
 'CKY - Conakry',
 'CKZ - Canakkale',
 'CLJ - Cluj-Napoca',
 'CLY - Calvi',
 'CMN - Casablanca',
 'CND - Constanta',
 'COO - Cotonou',
 'CPH - Copenhagen',
 'CRA - Craiova',
 'CRL - Brussels',
 'CRV - Crotone',
 'CTA - Catania',
 'CUF - Cuneo',
 'CWL - Cardiff',
 'CZL - Constantine',
 'DAM - Damascus',
 'DBV - Dubrovnik',
 'DEB - Debrecen',
 'DIY - Diyarbakir',
 'DJE - Djerba',
 'DLE - Dole',
 'DLM - Dalaman',
 'DMM - Dammam',
 'DND - Dundee',
 'DNZ - Denizli',
 'DOH - Doha',
 'DOL - Deauville',
 'DRS - Dresden',
 'DTM - Dortmund',
 'DUB - Dublin',
 'DUS - Dusseldorf',
 'DXB - Dubai',
 'DYU - Dushanbe',
 'EAM - Nejran',
 'EAS - San Sebastian',
 'EBA - Elba Island',
 'EBJ - Esbjerg',
 'EBL - Erbil',
 'ECN - Lefkosa',
 'EDI - Edinburgh',
 'EDO - Edremit/korfez',
 'EFL - Kefalonia',
 'EGC - Bergerac',
 'EIN - Eindhoven',
 'ELQ - Buraidah',
 'ELU - El Oued',
 'EMA - Derby',
 'ENU - Enugu',
 'ERC - Erzincan',
 'ERF - Erfurt',
 'ERH - Er-Rachidia',
 'ERZ - Erzurum',
 'ESB - Ankara',
 'ESU - Essaouira',
 'ETZ - Metz/nancy',
 'EUN - Laayoune',
 'EVE - Harstad-narvik',
 'EVN - Yerevan',
 'EXT - Exeter',
 'EZS - Elazig',
 'FAE - Sorvágur',
 'FAO - Faro',
 'FCO - Rome',
 'FDE - Forde',
 'FDH - Friedrichshafen',
 'FEG - Fergana',
 'FEZ - Fez',
 'FKB - Karlsruhe/Baden Baden',
 'FLR - Florence',
 'FLW - Flores Island',
 'FMM - Memmingen',
 'FMO - Muenster/Osnabrueck',
 'FNA - Freetown',
 'FNC - Funchal',
 'FNI - Nimes',
 'FRA - Frankfurt',
 'FRL - Forli',
 'FRO - Floro',
 'FRU - Bishkek',
 'FSC - Figari',
 'FUE - Puerto del Rosario',
 'GCI - Guernsey',
 'GDN - Gdansk',
 'GDQ - Gondar',
 'GHA - Ghardaia',
 'GIB - Gibraltar',
 'GIZ - Jazan',
 'GJL - Jijel',
 'GLA - Glasgow',
 'GLN - Goulimime',
 'GMZ - San Sebas De La Gomera',
 'GOA - Genova',
 'GOT - Gothenburg',
 'GPA - Patras',
 'GRO - Gerona',
 'GRQ - Groningen',
 'GRX - Granada',
 'GRZ - Graz',
 'GUW - Atyrau',
 'GVA - Geneva',
 'GWT - Westerland',
 'GYD - Baku',
 'GZT - Gaziantep',
 'HAD - Halmstad',
 'HAJ - Hanover',
 'HAM - Hamburg',
 'HAS - Hail',
 'HAU - Haugesund',
 'HBE - Alexandria',
 'HEL - Vantaa',
 'HER - Heraklion',
 'HFT - Hammerfest',
 'HHN - Hahn',
 'HMV - Hemavan',
 'HOF - Alahsa',
 'HOR - Horta',
 'HOV - Orsta-Volda',
 'HRG - Hurghada',
 'HUY - Humberside',
 'IAS - Iasi',
 'IBZ - Ibiza',
 'IEG - Zielona Gora',
 'IFN - Isfahan',
 'INI - Nis',
 'INN - Innsbruck',
 'INV - Inverness',
 'IOA - Ioannina',
 'IOM - Isle Of Man',
 'IST - Istanbul',
 'IVL - Ivalo',
 'JED - Jeddah',
 'JER - Jersey',
 'JIJ - Jijiga',
 'JIK - Ikaria Island',
 'JKH - Chios',
 'JMK - Mikonos',
 'JNX - Naxos',
 'JOE - Joensuu',
 'JSH - Sitia',
 'JSI - Skiathos',
 'JSY - Syros Island',
 'JTR - Santorini',
 'JYV - Jyvaskyla',
 'KAJ - Kajaani',
 'KAN - Kano',
 'KAO - Kuusamo',
 'KCM - Kahramanmaras',
 'KEF - Reykjavik',
 'KEM - Kemi/Tornio',
 'KFS - Kastamonu',
 'KGF - Karaganda',
 'KGS - Kos',
 'KIK - Kirkuk',
 'KIR - Farranfore',
 'KIT - Kithira',
 'KKN - Kirkenes',
 'KLR - Kalmar',
 'KLU - Klagenfurt',
 'KLV - Karlovy Vary',
 'KLX - Kalamata',
 'KOI - Orkney Island',
 'KOK - Kokkola/Pietarsaari',
 'KRF - Kramfors',
 'KRK - Krakow',
 'KRN - Kiruna',
 'KRS - Kristiansand',
 'KSC - Kosice',
 'KSD - Karlstad',
 'KSF - Kassel',
 'KSN - Kostanay',
 'KSU - Kristiansund',
 'KSY - Kars',
 'KTT - Kittila',
 'KTW - Katowice',
 'KUN - Kaunas',
 'KUO - Kuopio',
 'KUT - Kutaisi',
 'KVA - Kavala',
 'KWI - Kuwait City',
 'KYA - Konya',
 'KZS - Kastelorizo',
 'LBA - Leeds',
 'LBC - Lübeck',
 'LCA - Larnaca',
 'LCG - La Coruna',
 'LCJ - Lodz',
 'LCY - London',
 'LDE - Lourdes/Tarbes',
 'LDY - Derry',
 'LEI - Almeria',
 'LEJ - Leipzig-halle',
 'LEN - Leon',
 'LFW - Lome',
 'LGG - Liege',
 'LGW - London',
 'LHR - London',
 'LIG - Limoges',
 'LIL - Lille',
 'LIN - Milan',
 'LIS - Lisbon',
 'LJU - Ljubljana',
 'LKL - Lakselv',
 'LKN - Leknes',
 'LLA - Lulea',
 'LMP - Lampedusa',
 'LNZ - Linz',
 'LOS - Lagos',
 'LPA - Las Palmas',
 'LPI - Linkoping',
 'LPL - Liverpool',
 'LPP - Lappeenranta',
 'LRH - La Rochelle',
 'LRS - Leros',
 'LSI - Shetland Islands',
 'LTN - Luton',
 'LUX - Luxembourg',
 'LUZ - Lushan',
 'LXR - Luxor',
 'LXS - Limnos',
 'LYC - Lycksele',
 'LYR - Longyearbyen',
 'LYS - Lyon',
 'MAD - Madrid',
 'MAH - Menorca',
 'MAN - Manchester',
 'MCT - Muscat',
 'MED - Madinah',
 'MHD - Mashad',
 'MHG - Mannheim',
 'MHQ - Mariehamn',
 'MIR - Monastir',
 'MJF - Mosjoen',
 'MJI - Mitiga',
 'MJT - Mytilene',
 'MLA - Gudja',
 'MLH - Basel Mulhouse Freiburg',
 'MLN - Melilla',
 'MLO - Milos',
 'MLX - Malatya',
 'MME - Teesside, Durham',
 'MMX - Malmo',
 'MOL - Molde',
 'MPL - Montpellier',
 'MQM - Mardin',
 'MQN - Mo I Rana',
 'MRA - Misurata',
 'MRS - Marseille',
 'MSQ - Minsk',
 'MST - Maastricht',
 'MUC - Munich',
 'MUH - Mersa Matruh',
 'MXP - Milan',
 'MZH - Merzifon',
 'NAJ - Nakhichevan',
 'NAP - Napoli',
 'NCE - Nice',
 'NCL - Newcastle',
 'NDB - Nouadhibou',
 'NDR - Nador',
 'NIM - Niamey',
 'NKC - Nouakchott',
 'NOC - Knock',
 'NQY - Newquay',
 'NRK - Norrkoping',
 'NRN - Dusseldorf',
 'NTE - Nantes',
 'NUE - Nürnberg',
 'NWI - Norwich',
 'NYO - Stockholm',
 'OHD - Ohrid',
 'OLA - Orland',
 'OLB - Olbia',
 'OMH - Urmieh',
 'OMO - Mostar',
 'OMR - Oradea',
 'ONQ - Zonguldak',
 'OPO - Porto',
 'ORB - Orebro',
 'ORK - Cork',
 'ORN - Oran',
 'ORY - Paris',
 'OSD - Ostersund',
 'OSI - Osijek',
 'OSL - Oslo',
 'OSR - Ostrava',
 'OSS - Osh',
 'OST - Ostend',
 'OSY - Namsos',
 'OTP - Bucharest',
 'OUA - Ouagadougou',
 'OUD - Oujda',
 'OUL - Oulu',
 'OVD - Oviedo/Aviles',
 'OXB - Bissau',
 'OZZ - Ouarzazate',
 'PAD - Paderborn',
 'PAS - Paros',
 'PDL - Ponta Delgada, Azores',
 'PDV - Plovdiv',
 'PED - Pardubice',
 'PEG - Perugia',
 'PFO - Paphos',
 'PGF - Perpignan',
 'PHC - Port Harcourt',
 'PIK - Prestwick, South Ayrshire',
 'PIS - Poitiers',
 'PIX - Pico Island',
 'PLQ - Klaipeda/Palanga',
 'PLX - Semipalatinsk',
 'PMF - Parma',
 'PMI - Palma Mallorca',
 'PMO - Palermo',
 'PNA - Pamplona',
 'PNL - Pantelleria',
 'POZ - Poznan',
 'PRG - Prague',
 'PRN - Prishtina',
 'PSA - Pisa',
 'PSR - Pescara',
 'PUF - Pau',
 'PUY - Pula',
 'PVK - Preveza/Lefkas',
 'PXO - Porto Santo',
 'PZU - Port Sudan',
 'QSF - Setif',
 'RAE - Arar',
 'RAI - Praia',
 'RAK - Marrakech',
 'RBA - Rabat',
 'RDZ - Rodez',
 'REG - Reggio Calabria',
 'REU - Reus',
 'RHO - Rhodes',
 'RIX - Riga',
 'RJK - Rijeka',
 'RJL - Logrono',
 'RKT - Ras Al Khaimah',
 'RLG - Rostock-laage',
 'RMF - Marsa Alam',
 'RMI - Rimini',
 'RNN - Rønne',
 'RNS - Rennes',
 'ROB - Monrovia',
 'RRS - Roros',
 'RSI - Rio Sidra',
 'RTM - Rotterdam',
 'RUH - Riyadh',
 'RVK - Roervik',
 'RVN - Rovaniemi',
 'RZE - Rzeszow',
 'SAW - Istanbul',
 'SBZ - Sibiu',
 'SCN - Saarbruecken',
 'SCO - Aktau',
 'SCQ - Santiago De Compostela',
 'SCV - Suceava',
 'SDL - Sundsvall',
 'SDR - Santander',
 'SEN - Southend',
 'SFA - Sfax',
 'SFT - Skelleftea',
 'SGD - Sonderborg',
 'SHJ - Sharjah',
 'SHW - Sharurah',
 'SID - Sal',
 'SJJ - Sarajevo',
 'SKD - Samarkand',
 'SKG - Thessaloniki',
 'SKN - Stokmarknes',
 'SKP - Skopje',
 'SLL - Salalah',
 'SMI - Samos',
 'SNN - Shannon',
 'SOF - Sofia',
 'SOG - Sogndal',
 'SOU - Eastleigh near Southampton',
 'SPC - Santa Cruz De La Palma',
 'SPU - Split',
 'SSH - Sharm El Sheikh',
 'SSJ - Sandnessjoen',
 'STN - London',
 'STR - Stuttgart',
 'SUF - Lamezia-terme',
 'SUJ - Satu Mare',
 'SVG - Stavanger',
 'SVJ - Svolvaer',
 'SVQ - Sevilla',
 'SXB - Strasbourg',
 'SXZ - Siirt',
 'SYZ - Shiraz',
 'SZF - Samsun',
 'SZG - Salzburg',
 'SZY - Szymany',
 'SZZ - Szczecin',
 'TAS - Tashkent',
 'TAT - Poprad',
 'TAY - Tartu',
 'TBS - Tbilisi',
 'TBZ - Tabriz',
 'TER - Terceira Island',
 'TFN - Tenerife',
 'TFS - Tenerife',
 'TGD - Podgorica',
 'TGM - Tirgu Mures',
 'TIA - Tirana',
 'TIF - Taif',
 'TIN - Tindouf',
 'TIP - Tripoli',
 'TIV - Tivat',
 'TJK - Tokat',
 'TKU - Turku',
 'TLL - Tallinn',
 'TLM - Tlemcen',
 'TLN - Hyeres',
 'TLS - Toulouse',
 'TLV - Tel Aviv Yafo',
 'TMP - Tampere',
 'TMX - Timimoun',
 'TNG - Tangier',
 'TOE - Tozeur',
 'TOS - Tromso',
 'TPS - Trapani',
 'TRD - Trondheim',
 'TRF - Torp',
 'TRN - Turin',
 'TRS - Trieste',
 'TSF - Treviso',
 'TSR - Timisoara',
 'TTU - Tetuan',
 'TUF - Tours',
 'TUI - Turaif',
 'TUN - Tunis',
 'TUU - Tabuk',
 'TZL - Tuzla',
 'TZX - Trabzon',
 'UGC - Urgench',
 'UKK - Ust-kamenogorsk',
 'UME - Umea',
 'URA - Uralsk',
 'VAA - Vaasa',
 'VAN - Van',
 'VAR - Varna',
 'VAS - Sivas',
 'VBY - Visby',
 'VCE - Venice',
 'VDE - Valverde',
 'VGO - Vigo',
 'VIE - Vienna',
 'VIL - Dakhla',
 'VIT - Vitoria.',
 'VLC - Manises',
 'VLL - Valladolid',
 'VNO - Vilnius',
 'VOL - Volos',
 'VRN - Verona',
 'VST - Stockholm',
 'VXE - Sao Vicente',
 'VXO - Växjö',
 'WAW - Warsaw',
 'WRO - Wroclaw',
 'XCR - Chalons Sur Marne',
 'XRY - Jerez De La Frontera',
 'YNB - Yanbu',
 'ZAD - Zadar',
 'ZAG - Zagreb',
 'ZAZ - Zaragoza',
 'ZRH - Zurich',
 'ZTH - Zakinthos'
]

Origin_Airports = []
for airport in OLD_Origin_Airports:
    # Split the string into code and city
    code, city = airport.split(' - ')
    # Create the new string in the desired format
    new_airport = f'{city} ({code})'
    # Append the new string to the new list
    Origin_Airports.append(new_airport)


old_destination_airports = [
 'AAE - Annaba',
 'AAL - Aalborg',
 'AAR - Aarhus',
 'ABJ - Abidjan',
 'ABV - Abuja',
 'ABZ - Aberdeen',
 'ACC - Accra',
 'ACE - Arrecife',
 'ACH - Altenrhein',
 'ADA - Adana',
 'ADB - Izmir',
 'ADD - Addis Ababa',
 'ADF - Adiyaman',
 'AES - Aalesund',
 'AEY - Akureyri',
 'AGA - Agadir',
 'AGH - Angelholm/Helsingborg',
 'AGP - Malaga',
 'AHB - Abha',
 'AHO - Alghero',
 'AHU - Al Hoceima',
 'AJA - Ajaccio',
 'AJF - Sakaka Al Jouf',
 'AJI - Agri',
 'AKX - Aktyubinsk',
 'ALA - Almaty',
 'ALC - Alicante',
 'ALF - Alta',
 'ALG - Algiers',
 'AMM - Amman',
 'AMS - Amsterdam',
 'ANR - Antwerp',
 'AOE - Eskisehir',
 'AOI - Ancona',
 'AOK - Karpathos',
 'AQI - Qaisumah',
 'AQJ - Aqaba',
 'ARN - Stockholm',
 'ASB - Ashgabat',
 'ASR - Kayseri',
 'ASW - Aswan',
 'ATH - Athens',
 'AUH - Abu Dhabi',
 'AUR - Aurillac',
 'AXD - Alexandroupolis',
 'AYT - Antalya',
 'BAH - Manama',
 'BAL - Batman',
 'BAY - Baia Mare',
 'BBU - Bucharest',
 'BCM - Bacau',
 'BCN - Barcelona',
 'BDS - Brindisi',
 'BDU - Bardufoss',
 'BEG - Belgrade',
 'BEM - Bossembele',
 'BEN - Benghazi',
 'BER - Berlin',
 'BES - Brest',
 'BEY - Beirut',
 'BFS - Belfast',
 'BGG - Bongouanou',
 'BGO - Bergen',
 'BGW - Baghdad',
 'BGY - Bergamo',
 'BHD - Belfast',
 'BHH - Bisha',
 'BHK - Bukhara',
 'BHX - Birmingham',
 'BIA - Bastia',
 'BIO - Bilbao',
 'BIQ - Biarritz',
 'BJA - Bejaia',
 'BJL - Banjul',
 'BJV - Milas',
 'BJZ - Badajoz',
 'BKO - Bamako',
 'BLJ - Batna',
 'BLL - Billund',
 'BLQ - Bologna',
 'BMA - Stockholm',
 'BNX - Banja Luka',
 'BOD - Bordeaux',
 'BOH - Bournemouth',
 'BOJ - Bourgas',
 'BOO - Bodo',
 'BRE - Bremen',
 'BRI - Bari',
 'BRN - Berne',
 'BRQ - Brno',
 'BRS - Bristol',
 'BRU - Brussels',
 'BSK - Biskra',
 'BSL - Mulhouse/basel',
 'BSR - Basra',
 'BTS - Bratislava',
 'BUD - Budapest',
 'BUS - Batumi',
 'BVA - Paris',
 'BVC - Boa Vista',
 'BVE - Brive-La-Gaillarde',
 'BWK - Bol',
 'BZG - Bydgoszcz',
 'BZO - Bolzano',
 'BZR - Beziers',
 'CAG - Cagliari',
 'CAI - Cairo',
 'CCF - Carcassonne',
 'CDG - Paris',
 'CFE - Clermont-Ferrand',
 'CFK - Chefornak, AK',
 'CFN - Carrickfinn',
 'CFR - Caen',
 'CFU - Kerkyra',
 'CGN - Cologne',
 'CHQ - Chania',
 'CIA - Rome',
 'CIT - Shimkent',
 'CIY - Comiso',
 'CKY - Conakry',
 'CKZ - Canakkale',
 'CLJ - Cluj-Napoca',
 'CLY - Calvi',
 'CMN - Casablanca',
 'CND - Constanta',
 'COO - Cotonou',
 'CPH - Copenhagen',
 'CRA - Craiova',
 'CRL - Brussels',
 'CRV - Crotone',
 'CTA - Catania',
 'CUF - Cuneo',
 'CWL - Cardiff',
 'CZL - Constantine',
 'DAM - Damascus',
 'DBV - Dubrovnik',
 'DEB - Debrecen',
 'DIY - Diyarbakir',
 'DJE - Djerba',
 'DLE - Dole',
 'DLM - Dalaman',
 'DMM - Dammam',
 'DND - Dundee',
 'DNZ - Denizli',
 'DOH - Doha',
 'DOL - Deauville',
 'DRS - Dresden',
 'DTM - Dortmund',
 'DUB - Dublin',
 'DUS - Dusseldorf',
 'DXB - Dubai',
 'DYU - Dushanbe',
 'EAM - Nejran',
 'EAS - San Sebastian',
 'EBA - Elba Island',
 'EBJ - Esbjerg',
 'EBL - Erbil',
 'ECN - Lefkosa',
 'EDI - Edinburgh',
 'EDO - Edremit/korfez',
 'EFL - Kefalonia',
 'EGC - Bergerac',
 'EIN - Eindhoven',
 'ELQ - Buraidah',
 'ELU - El Oued',
 'EMA - Derby',
 'ENU - Enugu',
 'ERC - Erzincan',
 'ERF - Erfurt',
 'ERH - Er-Rachidia',
 'ERZ - Erzurum',
 'ESB - Ankara',
 'ESU - Essaouira',
 'ETZ - Metz/nancy',
 'EUN - Laayoune',
 'EVE - Harstad-narvik',
 'EVN - Yerevan',
 'EXT - Exeter',
 'EZS - Elazig',
 'FAE - Sorvágur',
 'FAO - Faro',
 'FCO - Rome',
 'FDE - Forde',
 'FDH - Friedrichshafen',
 'FEG - Fergana',
 'FEZ - Fez',
 'FKB - Karlsruhe/Baden Baden',
 'FLR - Florence',
 'FLW - Flores Island',
 'FMM - Memmingen',
 'FMO - Muenster/Osnabrueck',
 'FNA - Freetown',
 'FNC - Funchal',
 'FNI - Nimes',
 'FRA - Frankfurt',
 'FRL - Forli',
 'FRO - Floro',
 'FRU - Bishkek',
 'FSC - Figari',
 'FUE - Puerto del Rosario',
 'GCI - Guernsey',
 'GDN - Gdansk',
 'GDQ - Gondar',
 'GHA - Ghardaia',
 'GIB - Gibraltar',
 'GIZ - Jazan',
 'GJL - Jijel',
 'GLA - Glasgow',
 'GLN - Goulimime',
 'GMZ - San Sebas De La Gomera',
 'GOA - Genova',
 'GOT - Gothenburg',
 'GPA - Patras',
 'GRO - Gerona',
 'GRQ - Groningen',
 'GRX - Granada',
 'GRZ - Graz',
 'GUW - Atyrau',
 'GVA - Geneva',
 'GWT - Westerland',
 'GYD - Baku',
 'GZT - Gaziantep',
 'HAD - Halmstad',
 'HAJ - Hanover',
 'HAM - Hamburg',
 'HAS - Hail',
 'HAU - Haugesund',
 'HBE - Alexandria',
 'HEL - Vantaa',
 'HER - Heraklion',
 'HFT - Hammerfest',
 'HHN - Hahn',
 'HMV - Hemavan',
 'HOF - Alahsa',
 'HOR - Horta',
 'HOV - Orsta-Volda',
 'HRG - Hurghada',
 'HUY - Humberside',
 'IAS - Iasi',
 'IBZ - Ibiza',
 'IEG - Zielona Gora',
 'IFN - Isfahan',
 'INI - Nis',
 'INN - Innsbruck',
 'INV - Inverness',
 'IOA - Ioannina',
 'IOM - Isle Of Man',
 'IST - Istanbul',
 'IVL - Ivalo',
 'JED - Jeddah',
 'JER - Jersey',
 'JIJ - Jijiga',
 'JIK - Ikaria Island',
 'JKH - Chios',
 'JMK - Mikonos',
 'JNX - Naxos',
 'JOE - Joensuu',
 'JSH - Sitia',
 'JSI - Skiathos',
 'JSY - Syros Island',
 'JTR - Santorini',
 'JYV - Jyvaskyla',
 'KAJ - Kajaani',
 'KAN - Kano',
 'KAO - Kuusamo',
 'KCM - Kahramanmaras',
 'KEF - Reykjavik',
 'KEM - Kemi/Tornio',
 'KFS - Kastamonu',
 'KGF - Karaganda',
 'KGS - Kos',
 'KIK - Kirkuk',
 'KIR - Farranfore',
 'KIT - Kithira',
 'KKN - Kirkenes',
 'KLR - Kalmar',
 'KLU - Klagenfurt',
 'KLV - Karlovy Vary',
 'KLX - Kalamata',
 'KOI - Orkney Island',
 'KOK - Kokkola/Pietarsaari',
 'KRF - Kramfors',
 'KRK - Krakow',
 'KRN - Kiruna',
 'KRS - Kristiansand',
 'KSC - Kosice',
 'KSD - Karlstad',
 'KSF - Kassel',
 'KSN - Kostanay',
 'KSU - Kristiansund',
 'KSY - Kars',
 'KTT - Kittila',
 'KTW - Katowice',
 'KUN - Kaunas',
 'KUO - Kuopio',
 'KUT - Kutaisi',
 'KVA - Kavala',
 'KWI - Kuwait City',
 'KYA - Konya',
 'KZS - Kastelorizo',
 'LBA - Leeds',
 'LBC - Lübeck',
 'LCA - Larnaca',
 'LCG - La Coruna',
 'LCJ - Lodz',
 'LCY - London',
 'LDE - Lourdes/Tarbes',
 'LDY - Derry',
 'LEI - Almeria',
 'LEJ - Leipzig-halle',
 'LEN - Leon',
 'LFW - Lome',
 'LGG - Liege',
 'LGW - London',
 'LHR - London',
 'LIG - Limoges',
 'LIL - Lille',
 'LIN - Milan',
 'LIS - Lisbon',
 'LJU - Ljubljana',
 'LKL - Lakselv',
 'LKN - Leknes',
 'LLA - Lulea',
 'LMP - Lampedusa',
 'LNZ - Linz',
 'LOS - Lagos',
 'LPA - Las Palmas',
 'LPI - Linkoping',
 'LPL - Liverpool',
 'LPP - Lappeenranta',
 'LRH - La Rochelle',
 'LRS - Leros',
 'LSI - Shetland Islands',
 'LTN - Luton',
 'LUX - Luxembourg',
 'LUZ - Lushan',
 'LXR - Luxor',
 'LXS - Limnos',
 'LYC - Lycksele',
 'LYR - Longyearbyen',
 'LYS - Lyon',
 'MAD - Madrid',
 'MAH - Menorca',
 'MAN - Manchester',
 'MCT - Muscat',
 'MED - Madinah',
 'MHD - Mashad',
 'MHG - Mannheim',
 'MHQ - Mariehamn',
 'MIR - Monastir',
 'MJF - Mosjoen',
 'MJI - Mitiga',
 'MJT - Mytilene',
 'MLA - Gudja',
 'MLH - Basel Mulhouse Freiburg',
 'MLN - Melilla',
 'MLO - Milos',
 'MLX - Malatya',
 'MME - Teesside, Durham',
 'MMX - Malmo',
 'MOL - Molde',
 'MPL - Montpellier',
 'MQM - Mardin',
 'MQN - Mo I Rana',
 'MRA - Misurata',
 'MRS - Marseille',
 'MSQ - Minsk',
 'MST - Maastricht',
 'MUC - Munich',
 'MUH - Mersa Matruh',
 'MXP - Milan',
 'MZH - Merzifon',
 'NAJ - Nakhichevan',
 'NAP - Napoli',
 'NCE - Nice',
 'NCL - Newcastle',
 'NDB - Nouadhibou',
 'NDR - Nador',
 'NIM - Niamey',
 'NKC - Nouakchott',
 'NOC - Knock',
 'NQY - Newquay',
 'NRK - Norrkoping',
 'NRN - Dusseldorf',
 'NTE - Nantes',
 'NUE - Nürnberg',
 'NWI - Norwich',
 'NYO - Stockholm',
 'OHD - Ohrid',
 'OLA - Orland',
 'OLB - Olbia',
 'OMH - Urmieh',
 'OMO - Mostar',
 'OMR - Oradea',
 'ONQ - Zonguldak',
 'OPO - Porto',
 'ORB - Orebro',
 'ORK - Cork',
 'ORN - Oran',
 'ORY - Paris',
 'OSD - Ostersund',
 'OSI - Osijek',
 'OSL - Oslo',
 'OSR - Ostrava',
 'OSS - Osh',
 'OST - Ostend',
 'OSY - Namsos',
 'OTP - Bucharest',
 'OUA - Ouagadougou',
 'OUD - Oujda',
 'OUL - Oulu',
 'OVD - Oviedo/Aviles',
 'OXB - Bissau',
 'OZZ - Ouarzazate',
 'PAD - Paderborn',
 'PAS - Paros',
 'PDL - Ponta Delgada, Azores',
 'PDV - Plovdiv',
 'PED - Pardubice',
 'PEG - Perugia',
 'PFO - Paphos',
 'PGF - Perpignan',
 'PHC - Port Harcourt',
 'PIK - Prestwick, South Ayrshire',
 'PIS - Poitiers',
 'PIX - Pico Island',
 'PLQ - Klaipeda/Palanga',
 'PLX - Semipalatinsk',
 'PMF - Parma',
 'PMI - Palma Mallorca',
 'PMO - Palermo',
 'PNA - Pamplona',
 'PNL - Pantelleria',
 'POZ - Poznan',
 'PRG - Prague',
 'PRN - Prishtina',
 'PSA - Pisa',
 'PSR - Pescara',
 'PUF - Pau',
 'PUY - Pula',
 'PVK - Preveza/Lefkas',
 'PXO - Porto Santo',
 'PZU - Port Sudan',
 'QSF - Setif',
 'RAE - Arar',
 'RAI - Praia',
 'RAK - Marrakech',
 'RBA - Rabat',
 'RDZ - Rodez',
 'REG - Reggio Calabria',
 'REU - Reus',
 'RHO - Rhodes',
 'RIX - Riga',
 'RJK - Rijeka',
 'RJL - Logrono',
 'RKT - Ras Al Khaimah',
 'RLG - Rostock-laage',
 'RMF - Marsa Alam',
 'RMI - Rimini',
 'RNN - Rønne',
 'RNS - Rennes',
 'ROB - Monrovia',
 'RRS - Roros',
 'RSI - Rio Sidra',
 'RTM - Rotterdam',
 'RUH - Riyadh',
 'RVK - Roervik',
 'RVN - Rovaniemi',
 'RZE - Rzeszow',
 'SAW - Istanbul',
 'SBZ - Sibiu',
 'SCN - Saarbruecken',
 'SCO - Aktau',
 'SCQ - Santiago De Compostela',
 'SCV - Suceava',
 'SDL - Sundsvall',
 'SDR - Santander',
 'SEN - Southend',
 'SFA - Sfax',
 'SFT - Skelleftea',
 'SGD - Sonderborg',
 'SHJ - Sharjah',
 'SHW - Sharurah',
 'SID - Sal',
 'SJJ - Sarajevo',
 'SKD - Samarkand',
 'SKG - Thessaloniki',
 'SKN - Stokmarknes',
 'SKP - Skopje',
 'SLL - Salalah',
 'SMI - Samos',
 'SNN - Shannon',
 'SOF - Sofia',
 'SOG - Sogndal',
 'SOU - Eastleigh near Southampton',
 'SPC - Santa Cruz De La Palma',
 'SPU - Split',
 'SSH - Sharm El Sheikh',
 'SSJ - Sandnessjoen',
 'STN - London',
 'STR - Stuttgart',
 'SUF - Lamezia-terme',
 'SUJ - Satu Mare',
 'SVG - Stavanger',
 'SVJ - Svolvaer',
 'SVQ - Sevilla',
 'SXB - Strasbourg',
 'SXZ - Siirt',
 'SYZ - Shiraz',
 'SZF - Samsun',
 'SZG - Salzburg',
 'SZY - Szymany',
 'SZZ - Szczecin',
 'TAS - Tashkent',
 'TAT - Poprad',
 'TAY - Tartu',
 'TBS - Tbilisi',
 'TBZ - Tabriz',
 'TER - Terceira Island',
 'TFN - Tenerife',
 'TFS - Tenerife',
 'TGD - Podgorica',
 'TGM - Tirgu Mures',
 'TIA - Tirana',
 'TIF - Taif',
 'TIN - Tindouf',
 'TIP - Tripoli',
 'TIV - Tivat',
 'TJK - Tokat',
 'TKU - Turku',
 'TLL - Tallinn',
 'TLM - Tlemcen',
 'TLN - Hyeres',
 'TLS - Toulouse',
 'TLV - Tel Aviv Yafo',
 'TMP - Tampere',
 'TMX - Timimoun',
 'TNG - Tangier',
 'TOE - Tozeur',
 'TOS - Tromso',
 'TPS - Trapani',
 'TRD - Trondheim',
 'TRF - Torp',
 'TRN - Turin',
 'TRS - Trieste',
 'TSF - Treviso',
 'TSR - Timisoara',
 'TTU - Tetuan',
 'TUF - Tours',
 'TUI - Turaif',
 'TUN - Tunis',
 'TUU - Tabuk',
 'TZL - Tuzla',
 'TZX - Trabzon',
 'UGC - Urgench',
 'UKK - Ust-kamenogorsk',
 'UME - Umea',
 'URA - Uralsk',
 'VAA - Vaasa',
 'VAN - Van',
 'VAR - Varna',
 'VAS - Sivas',
 'VBY - Visby',
 'VCE - Venice',
 'VDE - Valverde',
 'VGO - Vigo',
 'VIE - Vienna',
 'VIL - Dakhla',
 'VIT - Vitoria.',
 'VLC - Manises',
 'VLL - Valladolid',
 'VNO - Vilnius',
 'VOL - Volos',
 'VRN - Verona',
 'VST - Stockholm',
 'VXE - Sao Vicente',
 'VXO - Växjö',
 'WAW - Warsaw',
 'WRO - Wroclaw',
 'XCR - Chalons Sur Marne',
 'XRY - Jerez De La Frontera',
 'YNB - Yanbu',
 'ZAD - Zadar',
 'ZAG - Zagreb',
 'ZAZ - Zaragoza',
 'ZRH - Zurich',
 'ZTH - Zakinthos'
]

destination_airports = []
for airport in old_destination_airports:
    # Split the string into code and city
    code, city = airport.split(' - ')
    # Create the new string in the desired format
    new_airport = f'{city} ({code})'
    # Append the new string to the new list
    destination_airports.append(new_airport)
####

date_input_key1 = 'date_input_1'
date_input_key2 = 'date_input_2'


# Create the first row with three columns
col1, col2, col3 = st.columns(3)

with col1:
    text_input_1 = st.selectbox("Origin Airport", Origin_Airports)
    text_input_1 = text_input_1[-4:-1]
with col2:
    text_input_2 = st.selectbox("Destination Airport", destination_airports)
    text_input_2 = text_input_2[-4:-1]
with col3:
    text_input_3 = st.selectbox("Cabin Class", ["ECONOMY", "BUSINESS", "PREMIUMECONOMY", "FIRST"])

# Create the second row with three columns
col4, col5, col6 = st.columns(3)

with col4:
    text_input_4 = st.selectbox("Trip Type", ["ONE_WAY", "RETURN"])
with col5:
    text_input_5 = st.selectbox("Connection Flight", ["0", "1"])
with col6:
    text_input_6 = st.selectbox("Trip Length", ["1", "2", '3'])

# Create the third row with three columns
col7, col8, col9 = st.columns(3)

with col7:
    text_input_7 = st.date_input("Prediction Date", key=date_input_key2, value=date.today(), min_value=date(1900, 1, 1), max_value=date(2100, 12, 31))
with col8:
    text_input_8 = st.date_input("Flight Date", key=date_input_key1, value=date.today(), min_value=date(1900, 1, 1), max_value=date(2100, 12, 31))
with col9:
    text_input_9 = st.selectbox("Airline", [
        "FR - Ryanair", "U2 - easyJet", "VY - Vueling", "PC - Pegasus Airlines",
        "W4 - Wizz Air Malta", "EW - Eurowings", "LH - Lufthansa", "W6 - Wizz Air",
        "RR - Buzz (Ryanair Sun)", "TK - Turkish Airlines", "A3 - Aegean Airlines",
        "XQ - SunExpress", "TO - Transavia France", "VF - Volaris", "BA - British Airways",
        "LS - Jet2.com", "LW - Lauda Europe", "OS - Austrian Airlines", "W9 - Wizz Air UK",
        "HV - Transavia"
    ])
    text_input_9 = text_input_9[:2]


# Button
bt = st.button("Look into the future! 🔮")

st.write("---")

# Title
st.write("Predicted flight fare:")

# Placeholder for the predicted price
price_placeholder = st.empty()

logo_url = "https://1000logos.net/wp-content/uploads/2020/03/Ryanair-Logo.png"

# Initialize price variable
price = "127 Euro"  # Default value

if text_input_1 and text_input_2 and text_input_3 and text_input_4 and text_input_5 and text_input_6 and text_input_7 and text_input_8 and text_input_9 and bt:
    BASE_URL = 'https://takeoff-final-image-uh7ydm6w2q-ew.a.run.app/'
    endpoint = 'predict'
    params = {
        'origin_air': text_input_1,
        'dest_air': text_input_2,
        'cab_class': text_input_3,
        'trip_type': text_input_4,
        'is_connected': text_input_5,
        'trip_len': text_input_6,
        'search_date': text_input_7,
        'flight_date': text_input_8,
        'airline': text_input_9
    }

    # Make the GET request
    response = requests.get(f'{BASE_URL}{endpoint}', params=params)

    # Print the response
    if response.status_code == 200:
        price = f"€ {response.json()['price']}"

    # Display the table row with dynamic price
    html_content = f"""
    <div style='display: flex; align-items: center; padding: 10px; border-bottom: 1px solid #ddd;'>
        <div style='flex: 1; text-align: center;'>
            <img src='{logo_url}' alt='Ryanair Logo' style='height: 100px; max-width: 100%; object-fit: contain;' />
        </div>
        <div style='flex: 1; text-align: center; font-size: 20px; color: green;'>
            {price}
        </div>
    </div>
    """
    st.markdown(html_content, unsafe_allow_html=True)
